menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/kuailederena
    GitHub: https://github.com/prototypezhou
    Rss: /atom.xml

favicon: https://avatars0.githubusercontent.com/u/18300865?v=3&s=40
logo: https://avatars0.githubusercontent.com/u/18300865?v=3&s=60

# Comment
# e.g disqus: seansun
disqus:
duoshuo: prototype

# Analytics
# google-analytics:
ga: UA-65933410-1
# baidu-analytics:
ba: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
