menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/kuailederena
    GitHub: https://github.com/prototypez
    Rss: /atom.xml

favicon: https://avatars0.githubusercontent.com/u/18300865?v=3&s=40
logo: https://avatars0.githubusercontent.com/u/18300865?v=3&s=120

# Comment
# e.g disqus: seansun
disqus:
duoshuo: prototypez

# Analytics
# google-analytics:
ga: UA-76153093-1
# baidu-analytics:
ba: //hm.baidu.com/hm.js?0ccb482127338efcdd63fb82acbe28c9

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
